### ISSUE TITLE
Add wait for add_ons to become available

### ISSUE THREAD

**Issue by aliabbasjaffri** [scott-the-programmer/terraform-provider-minikube#170]
Currently setting [wait](https://registry.terraform.io/providers/scott-the-programmer/minikube/latest/docs/resources/cluster#wait) for `add_ons` for minikube cluster with docker driver is not working. I am setting the wait as `wait = ["all", "apps_running"]`, however that does not work and other helm charts start getting applied to the cluster before waiting for `add_ons` to be installed, and failing, as add_ons are necessary to be available, such as ingress controller.

**Comment by scott-the-programmer** [comment]
Thanks for reporting this! I'm reasonably confident [this PR](https://github.com/scott-the-programmer/terraform-provider-minikube/pull/171) will fix the issue. 

I'll try polish up the PR later tonight and cut a new release 👍🏽

**Comment by scott-the-programmer** [comment]
> What should be the right option for the `wait` variable here? I'm still seeing the same issue with the error:
> 
> ```shell
> * Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.109.190.7:443: connect: connection refused
> ```

You can try wait = [ "all" ] which will wait for all components. I think in this case, the ingress is coming up and marked as running, but the pod isn't yet healthy. I don't think there's a way in minikube to wait for the ingress to be healthy - but i think you could achieve it via 

```terraform
 resource "kubernetes_job" "wait_for_ingress_nginx" {
  metadata {
    name      = "wait-for-ingress-nginx"
    namespace = "kube-system"
  }

  spec {
    template {
      metadata {
        name = "wait-for-ingress-nginx"
      }
      spec {
        container {
          name    = "kubectl"
          image   = "bitnami/kubectl:latest"
          command = ["/bin/sh", "-c"]
          args = [
            "kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=300s"
          ]
        }
        restart_policy = "Never"
      }
    }
    backoff_limit = 4
  }

  wait_for_completion = true

  timeouts {
    create = "5m"
  }
}
```

**Comment by aliabbasjaffri** [comment]
I just tried setting `wait` to `["all"]` and i get the following error:
```sh
Error: invalid wait option(s): all
```
However thanks for the tip above, i managed to make it work :-)
