### ISSUE TITLE
disk size units other than mb lead to destroyment of cluster

### ISSUE THREAD

**Issue by eddykaya** [scott-the-programmer/terraform-provider-minikube#176]
I am using the following definition for a minikube cluster

```terraform
resource "minikube_cluster" "local" {
  driver       = "kvm2"
  cluster_name = var.minikube_cluster_name
  nodes        = 1
  addons = [
    "dashboard",
    "default-storageclass",
    "ingress",
    "storage-provisioner",
    "registry",
    "registry-aliases"
  ]
  cni = "bridge"
  disk_size = "80g"
}
```

When I ran `terraform apply` without any changes, the provider wants to recreate the whole cluster because it does not recognize the disk size unit correctly.

If I use the following definition

```terraform
resource "minikube_cluster" "local" {
  driver       = "kvm2"
  cluster_name = var.minikube_cluster_name
  nodes        = 1
  addons = [
    "dashboard",
    "default-storageclass",
    "ingress",
    "storage-provisioner",
    "registry",
    "registry-aliases"
  ]
  cni = "bridge"
  disk_size = "81920mb"
}
```

it recognizes the disk size unit correctly and does not want to recreate the cluster

**Expected behaviour**
I can use any documented disk size unit without leading to unnecessary recreations of the whole cluster

**Comment by scott-the-programmer** [comment]
Thanks for reporting this! I've merged and released a fix for v0.4.4 😄 https://github.com/scott-the-programmer/terraform-provider-minikube/releases/tag/v0.4.4
