### ISSUE TITLE
docs: provide kvm2 driver configuration instructions for debian linux

### ISSUE THREAD

**Issue by caerulescens** [scott-the-programmer/terraform-provider-minikube#35]
The operating system I use for development is always stable debian, so I actually know the exact steps to configure `libvirt` with `minikube` on debian. I think it would be a good idea to remove the "living dangerously" section from the readme and just provide the actual steps to configure `libvirt` to work with `minikube`. I think the idea of danger might make less people use the provider as well. Maybe make a note about bugged minikube states from partial initialization; solution is `rm ~/.minikube` to reset minikube's state.

**Comment by caerulescens** [comment]
@scott-the-programmer I'll prepare a PR for this unless you have some objection.

**Comment by caerulescens** [comment]
The [driver](https://github.com/scott-the-programmer/terraform-provider-minikube/blob/9680135ebe78bc33b62b2f4385cd637ccd2cb1c8/docs/resources/cluster.md?plain=1#L120) field in the resouce documentation should list `kvm2` as an option as well.

**Comment by scott-the-programmer** [comment]
Good idea! The "living dangerously" script is supposed to be a generic download script that will set up any driver - this is if the user didn't want to install `minikube` at all. However, I agree in that it's probably not needed and does more harm than good

IMO I reckon we can just point people to https://minikube.sigs.k8s.io/docs/drivers/ which runs through the prereq steps here https://wiki.debian.org/KVM#Installation

**Comment by caerulescens** [comment]
Yep, that's exactly what I had in mind.
