### ISSUE TITLE
Would you be able to document what attributes this supports?

### ISSUE THREAD

**Issue by red8888** [scott-the-programmer/terraform-provider-minikube#96]
This is really great, I think it would be valuable to have on your main doc page for users: https://github.com/scott-the-programmer/terraform-provider-minikube/blob/main/examples/resources/minikube_cluster/resource.tf#L28

I also want to confirm, are the attributes driver specific? That example is doing `minikube_cluster.docker.*`, are those attributes only supported for the docker driver?

Thanks! I want to hook up the helm provider to the minikube cluster like this.

**Comment by scott-the-programmer** [comment]
You're entirely right! The [output attributes](https://registry.terraform.io/providers/scott-the-programmer/minikube/latest/docs/resources/cluster#read-only) are a huge part of how the provider links to other k8s providers such as helm. I will definitely flesh out the docs a bit more to highlight this 👍🏼 

To answer your question - no, the outputs aren't tied to a specific driver. Any driver will produce a client key/certificate, and the ca certificate used by the cluster. These values not only can plug into other k8s providers, but they can be exported in used in most k8s tools outside of terraform
